config/routes.rb
Rails.application.routes.draw do
  resources :image_comments
  resources :images
  root 'static_pages#home'

  devise_for :users

end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file,ImageUploader
    belongs_to :user
    has_many :image_comment, -> { order "created_at DESC"}
end

app/models/image_comment.rb
class ImageComment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/image_comments_controller.rb
class ImageCommentsController < ApplicationController
  before_action :set_image_comment, only: [:show, :edit, :update, :destroy]

  # GET /image_comments
  # GET /image_comments.json
  def index
    @image_comments = ImageComment.all
  end

  # GET /image_comments/1
  # GET /image_comments/1.json
  def show
  end

  # GET /image_comments/new
  def new
    @image_comment = ImageComment.new
  end

  # GET /image_comments/1/edit
  def edit
  end

  # POST /image_comments
  # POST /image_comments.json
  def create
    @image_comment = ImageComment.new(image_comment_params)
    @image_comment.user_id =current_user.id
    respond_to do |format|
      if @image_comment.save
        url = "/images/" + @image_comment.image_id.to_s
        format.html { redirect_to url, notice: 'Image comment was successfully created.' }
        format.json { render :show, status: :created, location: @image_comment }
      else
        format.html { render :new }
        format.json { render json: @image_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_comments/1
  # PATCH/PUT /image_comments/1.json
  def update
    respond_to do |format|
      if @image_comment.update(image_comment_params)
        format.html { redirect_to @image_comment, notice: 'Image comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_comment }
      else
        format.html { render :edit }
        format.json { render json: @image_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_comments/1
  # DELETE /image_comments/1.json
  def destroy
    @image_comment.destroy
    respond_to do |format|
      format.html { redirect_to image_comments_url, notice: 'Image comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_comment
      @image_comment = ImageComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_comment_params
      params.require(:image_comment).permit(:user_id, :image_id, :comment)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image_comment =ImageComment.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_comments_helper.rb
module ImageCommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/image_comments/_form.html.erb
<%= form_for(@image_comment) do |f| %>
  <% if @image_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_comment.errors.count, "error") %> prohibited this image_comment from being saved:</h2>

      <ul>
      <% @image_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.number_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_comments/edit.html.erb
<h1>Editing Image Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_comment %> |
<%= link_to 'Back', image_comments_path %>

app/views/image_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Image Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_comments.each do |image_comment| %>
      <tr>
        <td><%= image_comment.user_id %></td>
        <td><%= image_comment.image_id %></td>
        <td><%= image_comment.comment %></td>
        <td><%= link_to 'Show', image_comment %></td>
        <td><%= link_to 'Edit', edit_image_comment_path(image_comment) %></td>
        <td><%= link_to 'Destroy', image_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image comment', new_image_comment_path %>

app/views/image_comments/new.html.erb
<h1>New Image Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', image_comments_path %>

app/views/image_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image_comment.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @image_comment.image_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @image_comment.comment %>
</p>

<%= link_to 'Edit', edit_image_comment_path(@image_comment) %> |
<%= link_to 'Back', image_comments_path %>

app/views/images/_form.html.erb
<%= form_for(@image,{multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'タイトル' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'アップロードする画像' %><br>
    <%= f.file_field :file %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>File</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image.file %></td>
        <td><%= image.created_at %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Comment</h2>
<%= form_for(@image_comment) do |f| %>
<div class="field">
  <%= f.label :comment %><br>
  <%= f.text_field :comment %>
  <%= f.hidden_field :image_id, :value => @image.id %>
</div>
<h2>comment2</h2>
<ul>
<% @image.image_comment.each do |image_comment| %>
  <li><%=image_comment.comment %>
  (<i><%= image_comment.user_id %></i>)</li>
<%end%>
</ul>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>
<p>
  <strong>User:</strong>
  <%= @image.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>File:</strong>
  <%= image_tag @image.file %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @image.created_at %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PANDA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
    
  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }
  .navbar-brand{
    padding: 13px 15px;
  }
  .navbar-brand img{
    width: 30px;
  }
  .glyphicon-log-in{
    margin-right: 6px;
  }
  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; 
    }
  }
  </style>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/"><img src="image/panda2.png" ></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="#"><%= current_user.email %></a></li>
          <li><a data-method="delete" href="/users/sign_out"><span class="glyphicon glyphicon-log-in"></span>Sign out</a></li>
        <% else %>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span>Sign in</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>
</body>
</html>

app/views/static_pages/home.html.erb
<style>
    .carousel-inner{
        height: 100vh;
    }
    .carousel-caption{
        bottom: 0;
        top: 25%;
    }
    .carousel-caption h1{
        font-size: 48px; 
    }
</style>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="image/artic-sky3.jpg" alt="Image">
        <div class="carousel-caption">
          <h1>Home to everyone's best photos</h1> 
          <h3>Showcase your work, license amazing photos, and stay inspired.</h3>
        </div>      
      </div>
    </div>
</div>
  
<div class="container text-center">    
  <h3>What We Do</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Current Project</p>
    </div>
    <div class="col-sm-4"> 
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Project 2</p>    
    </div>
    <div class="col-sm-4">
      <div class="well">
       <p>Some text..</p>
      </div>
      <div class="well">
       <p>Some text..</p>
      </div>
    </div>
  </div>
</div><br>